FROM nginx:latest

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom Nginx config file from your system into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 8080 to the host so you can access the proxy
EXPOSE 8080

# Use the default command of the base image which starts Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
